// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yoksrcpcgtdyswdfgkrt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlva3NyY3BjZ3RkeXN3ZGZna3J0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4Mzk0NDcsImV4cCI6MjA1OTQxNTQ0N30.ZUl7iWC4yfb_avmn1m4Z-wN0CsbNLrzyqEy9TKEca3A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);